name: artlens
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  path: ^1.9.1
  sqflite: ^2.4.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Limelight
      fonts:
      - asset: assets/fonts/Limelight-Regular.ttf
    - family: RobotoCondensed
      fonts:
      - asset: assets/fonts/Roboto_Condensed-Black.ttf
       